# conda recipe for stable release on bsteubing channel
# https://anaconda.org/bsteubing/activity-browser
# this is mainly used for development purposes, use the official release instead at
# https://anaconda.org/conda-forge/activity-browser
package:
  name: activity-browser
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  # Note for future: https://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos
  git_rev: major
  git_url: https://github.com/LCA-ActivityBrowser/activity-browser.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"
  entry_points:
    - activity-browser = activity_browser_beta:run_activity_browser
    - activity-browser-cleanup = activity_browser.bwutils:cleanup

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.10, <3.12
    - conda
    - arrow
    - bw2analyzer >=0.11.5
    - bw2data >=4.1
    - bw2parameters >=1.1
    - bw2io >=0.9.3
    - bw_graph_tools >=0.5
    - bw_processing >=1.0
    - bw_simapro_csv >=0.2.6
    - bw_functional
    - ecoinvent_interface
    - matrix_utils >=0.5
    - numpy >=1.23.5, <2
    - pint <=0.21
    - pyperclip
    - pyprind
    - networkx
    - pandas >=2.2.1
    - pyside2 >=5.15.5
    - qt-webengine
    - qtpy
    - salib >=1.4, <1.5.1
    - seaborn

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: GUI for brightway2
  description: |
    The Activity Browser is a graphical user interface for the [brightway2](https://brightway.dev/)
    advanced life cycle assessment framework. More details and installation instructions can be found
    on [github](https://github.com/LCA-ActivityBrowser/activity-browser).
