# Used https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml as example
{% set version = "2.5.0" %}

package:
  name: activity-browser
  version: "{{ version }}"

source:
  # Note for future: https://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos
  git_rev: "{{ version }}"
  git_url: https://github.com/LCA-ActivityBrowser/activity-browser.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"
  entry_points:
    - activity-browser = activity_browser.app:run_activity_browser
    - activity-browser-cleanup = activity_browser.app.bwutils:cleanup

requirements:
  build:
    - python
    - setuptools
  run:
    - python<3.8  # https://github.com/conda-forge/pyside2-feedstock/issues/56
    - arrow
    - brightway2 >=2.1.2
    - bw2io >=0.7.dev1
    - bw2data >=3.6.1
    - eidl >=1.2.0
    - fuzzywuzzy
    - matplotlib-base >=2.2.2
    - networkx
    - pandas >=0.24.1
    - pyside2==5.13.1
    - seaborn
    - presamples

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: GUI for brightway2
  description: |
    The Activity Browser is a graphical user interface for the [brightway2](https://brightwaylca.org/)
    advanced life cycle assessment framework. More details and installation instructions can be found
    on [github](https://github.com/LCA-ActivityBrowser/activity-browser).
