package:
  name: activity-browser
  version: "{{ os.environ.get('VERSION', 'dev') }}"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"
  entry_points:
    - activity-browser = activity_browser:run_activity_browser
    - activity-browser-cleanup = activity_browser.bwutils:cleanup

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.10,<3.12
    - arrow
    - brightway2 =2.4.6
    - networkx
    - numpy >=1.23.5
    - pandas >=2.2.1
    - pint <=0.21
    - pyperclip
    - pyside2 >=5.15.5
    - qt-webengine
    - salib >=1.4
    - seaborn

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: GUI for brightway2
  description: |
    The Activity Browser is a graphical user interface for the [brightway2](https://brightway.dev/)
    advanced life cycle assessment framework. More details and installation instructions can be found
    on [github](https://github.com/LCA-ActivityBrowser/activity-browser).
