name: test
channels:
  - conda-forge
  - cmutel
  - bsteubing
dependencies:
  - pytest
  - pytest-qt
  - pytest-mock
  - python >=3.8,<3.10
  - arrow
  - brightway2 >=2.4.2
  - pyperclip
  - eidl >=1.4.2
  - networkx
  - pyside2 >=5.13.1
  - salib >=1.4
  - seaborn
