package:
  name: "{{ os.environ.get('PKG_NAME', 'activity-browser-dev') }}"
  version: "{{ os.environ.get('VERSION', 'dev') }}"

source:
  path: ../../..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"
  script_env:
    - PKG_NAME
    - VERSION
    - CONDA_BLD_PATH
  entry_points:
    - activity-browser = activity_browser:run_activity_browser
    - activity-browser-cleanup = activity_browser.bwutils:cleanup

requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.8, <=3.9  # https://github.com/conda-forge/pyside2-feedstock/issues/56
    - arrow
    - bokeh >=2.3.2
    - brightway2 >=2.1.2
    - bw2io >=0.8
    - bw2data >=3.6.1
    - eidl >=1.2.0
    - fuzzywuzzy
    - matplotlib-base >=2.2.2
    - networkx
    - pandas >=0.24.1
    - pyside2 >=5.13.1
    - python-chromedriver-binary
    - salib >=1.3.11
    - seaborn
    - selenium
    - presamples
    - openpyxl
    - xlrd<2.0  # https://github.com/brightway-lca/brightway2-io/issues/86

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: "{{ os.environ.get('SUMMARY', 'Development version of the Activity Browser') }}"
  description: |
    The Activity Browser is a graphical user interface for the [brightway2](https://brightwaylca.org/)
    advanced life cycle assessment framework. More details and installation instructions can be found
    on [github](https://github.com/LCA-ActivityBrowser/activity-browser).
    This is the development version. For the stable release install the `activity-browser` package.
