blank_issues_enabled: false
contact_links:
  - name: How to use AB
    url: https://github.com/LCA-ActivityBrowser/activity-browser/discussions
    about: Ask AB user questions on our discussions page.