blank_issues_enabled: false
contact_links:
  - name: Read the Wiki
    url: https://github.com/LCA-ActivityBrowser/activity-browser/wiki
    about: Learn how to use Activity Browser with the wiki.
  - name: Ask the community
    url: https://github.com/LCA-ActivityBrowser/activity-browser/discussions
    about: Ask the Activity Browser community for help on using Activity Browser.
  
