name: Something else
description: Open an issue for AB.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing this issue with us! In case you want help with using AB, please use the [discussions page](https://github.com/LCA-ActivityBrowser/activity-browser/discussions) instead.
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Please share the issue you're experiencing.
    validations:
      required: true
