from .activity.activity_delete import ActivityDelete
from .activity.activity_duplicate import ActivityDuplicate
from .activity.activity_duplicate_to_db import ActivityDuplicateToDB
from .activity.activity_duplicate_to_loc import ActivityDuplicateToLoc
from .activity.activity_graph import ActivityGraph
from .activity.activity_modify import ActivityModify
from .activity.activity_new import ActivityNew
from .activity.activity_open import ActivityOpen
from .activity.activity_relink import ActivityRelink
from .biosphere_update import BiosphereUpdate
from .calculation_setup.cs_delete import CSDelete
from .calculation_setup.cs_duplicate import CSDuplicate
from .calculation_setup.cs_new import CSNew
from .calculation_setup.cs_rename import CSRename
from .database.database_delete import DatabaseDelete
from .database.database_duplicate import DatabaseDuplicate
from .database.database_export import DatabaseExport
from .database.database_import import DatabaseImport
from .database.database_new import DatabaseNew
from .database.database_relink import DatabaseRelink
from .default_install import DefaultInstall
from .exchange.exchange_copy_sdf import ExchangeCopySDF
from .exchange.exchange_delete import ExchangeDelete
from .exchange.exchange_formula_remove import ExchangeFormulaRemove
from .exchange.exchange_modify import ExchangeModify
from .exchange.exchange_new import ExchangeNew
from .exchange.exchange_uncertainty_modify import ExchangeUncertaintyModify
from .exchange.exchange_uncertainty_remove import ExchangeUncertaintyRemove
from .method.cf_amount_modify import CFAmountModify
from .method.cf_new import CFNew
from .method.cf_remove import CFRemove
from .method.cf_uncertainty_modify import CFUncertaintyModify
from .method.cf_uncertainty_remove import CFUncertaintyRemove
from .method.method_delete import MethodDelete
from .method.method_duplicate import MethodDuplicate
from .parameter.parameter_clear_broken import ParameterClearBroken
from .parameter.parameter_delete import ParameterDelete
from .parameter.parameter_modify import ParameterModify
from .parameter.parameter_new import ParameterNew
from .parameter.parameter_new_automatic import ParameterNewAutomatic
from .parameter.parameter_rename import ParameterRename
from .parameter.parameter_uncertainty_modify import ParameterUncertaintyModify
from .parameter.parameter_uncertainty_remove import ParameterUncertaintyRemove
from .plugin_wizard_open import PluginWizardOpen
from .project.project_delete import ProjectDelete
from .project.project_duplicate import ProjectDuplicate
from .project.project_new import ProjectNew
from .project.project_switch import ProjectSwitch
from .settings_wizard_open import SettingsWizardOpen
