# conda recipe for activity-browser-dev
# https://anaconda.org/bsteubing/activity-browser-dev
package:
  name: "{{ os.environ.get('PKG_NAME', 'activity-browser-dev') }}"
  version: "{{ os.environ.get('VERSION', 'dev') }}"

source:
  path: ../..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"
  script_env:
    - PKG_NAME
    - VERSION
  entry_points:
    - activity-browser = activity_browser:run_activity_browser
    - activity-browser-cleanup = activity_browser.bwutils:cleanup

requirements:
  build:
    - python
    - setuptools
  run:  # dependencies are added via github action from stable at recipe/meta.yaml

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: "{{ os.environ.get('SUMMARY', 'Development version of the Activity Browser') }}"
  description: |
    The Activity Browser is a graphical user interface for the [brightway2](https://brightway.dev/)
    advanced life cycle assessment framework. More details and installation instructions can be found
    on [github](https://github.com/LCA-ActivityBrowser/activity-browser).
    This is the development version. For the stable release install the `activity-browser` package.
