# conda recipe for activity-browser-dev
# https://anaconda.org/bsteubing/activity-browser-dev
package:
  name: "activity-browser-dev25"
  version: "3.0.dev8"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  entry_points:
    - activity-browser = activity_browser:run_activity_browser
    - activity-browser-cleanup = activity_browser.bwutils:cleanup

requirements:
  build:
    - python
    - setuptools
  run:
    - arrow
    - bw2analyzer >=0.11.5
    - bw2calc >=2.0.dev20
    - bw2data >=4.0.dev52
    - bw2io >=0.9.dev37
    - bw_graph_tools >=0.5
    - bw_processing >=1.0
    - bw_simapro_csv >=0.2.4
    - ecoinvent_interface
    - libxml2 <=2.10.4
    - matrix_utils >=0.5
    - multifunctional >=0.7.1
    - networkx
    - numpy >=1.23.5,<2
    - pandas <=2.1.4
    - pint <=0.21
    - pyperclip
    - pyside2 >=5.15.5
    - python =3.11
    - qt-webengine
    - randonneur >=0.4
    - randonneur_data >=0.2.1
    - salib >=1.4
    - seaborn
    # Only needed for Windows but I don't want to set up a build farm...
    - sqlite-fts4

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: "Development version of the Activity Browser for Brightway 2.5"
  description: |
    The Activity Browser is a graphical user interface for the [brightway](https://brightway.dev/)
    advanced life cycle assessment framework. More details and installation instructions can be found
    on [github](https://github.com/LCA-ActivityBrowser/activity-browser).
    This is the development version. For the stable release install the `activity-browser` package.
