# Used https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml as example
package:
  name: activity-browser
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  # Note for future: https://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos
  git_rev: master
  git_url: https://github.com/LCA-ActivityBrowser/activity-browser.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"
  entry_points:
    - activity-browser = activity_browser:run_activity_browser
    - activity-browser-cleanup = activity_browser.bwutils:cleanup

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.8,<3.10
    - arrow
    - brightway2 >=2.4.2
    - eidl >=1.4
    - networkx
    - pyside2 >=5.13.1
    - salib >=1.4
    - seaborn
    - presamples

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: GUI for brightway2
  description: |
    The Activity Browser is a graphical user interface for the [brightway2](https://brightway.dev/)
    advanced life cycle assessment framework. More details and installation instructions can be found
    on [github](https://github.com/LCA-ActivityBrowser/activity-browser).
