name: Build Executable
on:
  push:
    branches: [ major ]
    tags: '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libxcb-shape0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install UV
        uses: astral-sh/setup-uv@v2

      - name: Sync dependencies
        shell: bash
        run: |
          uv add pyinstaller
          uv sync --prerelease=allow

      - name: Build executable with PyInstaller
        shell: bash
        run: |
          uv run pyinstaller --onefile --name activity-browser activity_browser/__main__.py

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
