name: stable conda release
on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy 3.8
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: build
          environment-file: ci/conda-envs/build.yml
      - name: Build activity-browser stable
        run: |
          conda build ci/recipe/stable
      - name: Upload to anaconda.org
        run: |
          anaconda -t ${{ secrets.CONDA_UPLOAD_TOKEN }} upload \
          /usr/share/miniconda/envs/build/conda-bld/noarch/*.tar.bz2
