name: canary installation
on:
  schedule:
    # Run the tests once every 24 hours to catch dependency problems early
    - cron: '0 7 * * *'

jobs:
  canary-installs-pip:
    timeout-minutes: 12
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15, macos-latest]
        py-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install activity-browser
        run: |
          python -m pip install activity-browser
      - name: Environment info
        run: |
          pip freeze
          pip freeze > requirements.txt
      - name: Upload final environment as artifact
        uses: actions/upload-artifact@v3
        with:
          name: requirements-${{ matrix.os }}-${{ matrix.python-version }}.txt
          path: requirements.txt