name: pypi - tests and development release
on:
  pull_request:
    branches:
      - main
      - minor
      - brightway25
  push:
    branches:
      - main
      - brightway25

jobs:

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13 ]
        python-version: [ '3.10' ]
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip & install testing pkgs
        run: |
          python -VV
          python -m pip install --upgrade pip setuptools wheel

      # install testing
      - name: Install package and test deps
        run: |
          pip install .[testing] # install the package and the testing deps
      - name: Install linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
        run: |
          sudo apt install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 \
            libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 \
            libxcb-xfixes0 xvfb x11-utils glibc-tools;
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid \
          --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 \
          1920x1200x24 -ac +extension GLX +render -noreset;
      - name: Run linux tests
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          QT_DEBUG_PLUGINS: 1
        run: |
          catchsegv xvfb-run --auto-servernum pytest --cov=activity_browser --cov-report=;
      - name: Run tests
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: |
          pytest

  deploy-development:
    # Make sure to only run a deploy if all tests pass.
    needs:
      - tests
    # And only on a push event, not a pull_request.
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      PKG_NAME: "activity-browser-dev25"
    steps:
      - name: Overwrite package name
        run: |
          sed -i "s/name = \"activity_browser\"/name=\"$PKG_NAME\"/" pyproject.toml
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --outdir dist/ .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
