name: github release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build changelog from PRs with labels
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: "ci/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Patch ab env with run requirements from stable recipe
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq eval-all -i 'select(fi == 0).dependencies += select(fi == 1).requirements.run | select(fi == 0)' ci/conda-envs/ab.yml ci/recipe/stable/meta.yaml
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          artifacts: 'ci/conda-envs/ab.yml'
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
