name: stable release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Build changelog from PRs with labels
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up conda-build environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          activate-environment: build
          environment-file: .github/conda-envs/build.yml
      - name: Build activity-browser stable
        run: |
          conda build recipe/
      - name: Upload to anaconda.org
        run: |
          anaconda -t ${{ secrets.CONDA_UPLOAD_TOKEN }} upload \
          /usr/share/miniconda/envs/build/conda-bld/noarch/*.tar.bz2
