name: Automated Testing
on:
  pull_request:
    branches:
      - major
  push:
    branches:
      - major

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        py-version: ["3.10", "3.11", "3.12"]
    env:
      DISPLAY: ':99.0'
    steps:
      - uses: actions/checkout@v4

      # general Python setup
      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}

      - name: Install linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
                  /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

      - name: Update pip & install testing pkgs
        run: |
          python -VV
          python -m pip install --upgrade pip setuptools wheel

      # install testing
      - name: Install package and test deps
        run: |
          pip install .[testing] # install the package and the testing deps

      - name: Test with pytest
        run: |
          pytest
